/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 17 05:13:26 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.MyQuickSort;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MyQuickSort_ESTest extends MyQuickSort_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[18];
      // Undeclared exception!
      try { 
        MyQuickSort.main(stringArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 12
         //
         assertThrownBy("edu.osu.cs362.MyQuickSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int[] intArray0 = new int[0];
      MyQuickSort myQuickSort0 = new MyQuickSort();
      myQuickSort0.sort(intArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int[] intArray0 = new int[1];
      MyQuickSort myQuickSort0 = new MyQuickSort();
      // Undeclared exception!
      try { 
        myQuickSort0.sort(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         assertThrownBy("edu.osu.cs362.MyQuickSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MyQuickSort myQuickSort0 = new MyQuickSort();
      myQuickSort0.sort((int[]) null);
  }
}
